# a workflow that runs when a user enters a pull request comment
# if the user enters "/cypress" we trigger the workflow "slash-command-cypress"
name: Slash Command Dispatch

on:
  issue_comment:
    types: [created]

jobs:
  slash_command_dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Slash Command Dispatch
        # https://github.com/peter-evans/slash-command-dispatch
        uses: peter-evans/slash-command-dispatch@v3
        with:
          # the built-in GitHub token when running actions
          token: ${{ secrets.GITHUB_TOKEN }}
          permission: none
          static-args: |
            repository=${{ github.repository }}
            comment-id=${{ github.event.comment.id }}
          commands: |
            cypress
