# this workflow runs when the user comments "/cypress" on a pull request
name: Slash Command (Cypress)

on:
  repository_dispatch:
    types: [cypress-command]

permissions:
  contents: read
  pull-requests: write

jobs:
  launc-tests:
    name: Launch API tests
    runs-on: ubuntu-latest
    steps:
      - name: Print event 🖨️
        run: |
          echo off
          echo '${{ toJson(github.event.client_payload.slash_command) }}'

      - name: Print PR event 🖨️
        run: |
          echo off
          echo '${{ toJson(github.event.client_payload.pull_request) }}'

      - name: Check out the repo 🛎️
        # https://github.com/actions/checkout
        uses: actions/checkout@v4
        with:
          # only check out one JS file
          # that we use to trigger workflow in the tests repo
          sparse-checkout: |
            .github/workflows/trigger-cypress.js
          sparse-checkout-cone-mode: false

      - name: Trigger Cypress run
        # https://github.com/actions/github-script
        uses: actions/github-script@v6
        id: trigger
        # pass this repo's name and PR number
        # plus the comment ID so the tests workflow can post results back
        env:
          REPO_NAME: ${{ github.event.client_payload.slash_command.args.named.repository }}
          PR_NUMBER: ${{ github.event.client_payload.pull_request.number }}
          REF: ${{ github.event.client_payload.slash_command.args.named.ref }}
          FEEDBACK_COMMENT_ID: ${{ github.event.client_payload.github.payload.comment.id }}
          COMMIT_SHA: ${{ github.event.client_payload.pull_request.head.sha }}
        with:
          # unfortunately we need to use a personal token to trigger
          # a workflow in another repo, cannot use just GITHUB_TOKEN
          github-token: ${{ secrets.PERSONAL_TOKEN }}
          script: |
            const result = await require('./.github/workflows/trigger-cypress.js')({ github, core });
            return result;
